kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
    - docker build . -t registry.mmskl.net/tkfmh_mmskl_net
    - echo "$$DOCKER_PASSWORD" | docker login --username "$$DOCKER_USER" --password-stdin registry.mmskl.net
    - docker push registry.mmskl.net/yotcaster_mmskl_net
  environment:
    DEBUG: 0
    DOCKER_USER:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock

- name: run
  image: docker/compose
  commands:
    - docker-compose -p tkfmh_mmskl_net up -d
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock


volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
